import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const jetBrainsMono = localFont({
  src: '../public/fonts/JETBRAINSMONONL-REGULAR.ttf',
  variable: "--font-jetbrains-mono"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
